---
- name: Netdata | Ensure apt-transport-https is installed
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - gpg
    state: present

- name: Netdata | Get apt key
  ansible.builtin.get_url:
    url: https://repository.netdata.cloud/netdatabot.gpg.key
    dest: /usr/share/keyrings/netdata-archive-keyring.asc
    mode: '0644'
    force: true

- name: Netdata | Verify GPG key fingerprint
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      gpg --show-keys --with-fingerprint --with-colons /usr/share/keyrings/netdata-archive-keyring.asc 2>/dev/null | grep -m 1 fpr | awk -F: '{print $10}'
  args:
    executable: /bin/bash
  register: gpg_fingerprint
  changed_when: gpg_fingerprint.rc != 0

- name: Netdata | Check if GPG fingerprint matches the expected value
  ansible.builtin.assert:
    that:
      - gpg_fingerprint.stdout.strip() == "{{ netdata_apt_gpg_fingerprint }}"
    fail_msg: "GPG fingerprint does not match the expected value."
    success_msg: "GPG fingerprint matches the expected value."

- name: Netdata | Ensure netdata apt repository is present
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/netdata-archive-keyring.asc] https://repository.netdata.cloud/repos/stable/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }}/"
    update_cache: true
    state: present

- name: Netdata | Ensure Netdata is installed
  ansible.builtin.apt:
    name: netdata
    state: present
