---
name: CI
"on":
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "30 4 * * 1"

defaults:
  run:
    working-directory: "chadek.netdata"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: "chadek.netdata"

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install test dependencies.
        run: pip3 install yamllint ansible-lint

      - name: Lint code.
        run: |
          yamllint .
          ansible-lint .

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: "chadek.netdata"

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-podman molecule-plugins[podman] podman

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
